variables:
- name: SolutionBaseName
  value: Dfc.Shared.Owasp

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    endpoint: 'GitHub (ESFA)'
    ref: refs/tags/v1.11.2

pool:
  name: 'NCS - CI and CD'
  demands:
    - PowerShell
    - AzurePS
    - docker

# trigger:
#   branches:
#     include:
#     - master
#     - dev

# pr:
#   branches:
#     include:
#     - master
#     - dev


stages:
- stage: BuildAndPublishContainers
  # condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.Reason'], 'PullRequest'))
  dependsOn: []
  variables:
  - group: KeyVault - dfc-dev-shared-kv
  - group: dfc-shared-dev
  jobs:
  - template: JobTemplates\BuildAndPublishLinuxContainers.yml
    parameters:
      ContainerRegistryAdminUser: $(ContainerRegistryAdminUser)
      ContainerRegistryPassword: $(ContainerRegistryPassword)

- stage: DeployOwaspToLab
  # condition: and(succeeded('BuildAndPublishContainers'), eq(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.Reason'], 'PullRequest'))
  dependsOn: BuildAndPublishContainers
  variables:
  - template: VariableTemplates\SharedEnvironmentVariables.yml
  - template: VariableTemplates\LabEnvironmentVariables.yml
  - group: KeyVault - dfc-lab-shared-kv
  - group: dfc-shared-lab
  - group: dfc-owasp-lab
  jobs:
  - template: JobTemplates\DeployContainers.yml
    parameters:
      AksResourceGroup: $(sharedResourceGroup)
      AzurePatToken: $(AzureDevOpsAgentPatToken)
      AzureSubscriptionEndpoint: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      Environment: LAB_SHARED
      KubernetesCluster: $(sharedAksCluster)
      Namespace: 'owasp'

- stage: DeployOwaspToDev
  # condition: and(succeeded('BuildAndPublishContainers'), eq(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.Reason'], 'PullRequest'))
  dependsOn: DeployOwaspToLab
  variables:
  - template: VariableTemplates\SharedEnvironmentVariables.yml
  - template: VariableTemplates\DevEnvironmentVariables.yml
  - group: KeyVault - dfc-dev-shared-kv
  - group: dfc-shared-dev
  - group: dfc-owasp-dev
  jobs:
  - template: JobTemplates\DeployContainers.yml
    parameters:
      AksResourceGroup: $(sharedResourceGroup)
      AzurePatToken: $(AzureDevOpsAgentPatToken)
      AzureSubscriptionEndpoint: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      Environment: DEV_SHARED
      KubernetesCluster: $(sharedAksCluster)
      Namespace: 'owasp'

- stage: DeployOwaspToSit
  # condition: and(succeeded('BuildAndPublishContainers'), eq(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.Reason'], 'PullRequest'))
  dependsOn: DeployOwaspToDev
  variables:
  - template: VariableTemplates\SharedEnvironmentVariables.yml
  - template: VariableTemplates\SitEnvironmentVariables.yml
  - group: KeyVault - dfc-sit-shared-kv
  - group: dfc-shared-sit
  - group: dfc-owasp-sit
  jobs:
  - template: JobTemplates\DeployContainers.yml
    parameters:
      AksResourceGroup: $(sharedResourceGroup)
      AzurePatToken: $(AzureDevOpsAgentPatToken)
      AzureSubscriptionEndpoint: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      Environment: SIT_SHARED
      KubernetesCluster: $(sharedAksCluster)
      Namespace: 'owasp'
            